### ISSUE TITLE
Relation to goproxy?

### ISSUE THREAD

**Issue by hazcod** [telanflow/mps#3]
Hi, is this project forked from https://github.com/elazarl/goproxy ?
What is the relation? Thank you.

**Comment by telanflow** [comment]
Yes, MPS has borrowed most of its code from [goproxy](https://github.com/elazarl/goproxy), but I want to implement a more powerful proxy framework, and MPS will later add more features, such as better handling of TCP, UDP, and superlayer protocols.

**Comment by hazcod** [comment]
Ok, is there a set of optimisations done since you mention performance?
I might fork your project instead.
