### ISSUE TITLE
Firefox: SSL_ERROR_RX_RECORD_TOO_LONG

### ISSUE THREAD

**Issue by hazcod** [telanflow/mps#4]
Hi, trying out your fork with below code, returns either `Secure Connection Failed` or `SSL_ERROR_RX_RECORD_TOO_LONG`. Anything I am doing wrong? No logs from mps.

```go
	proxyInstance := mps.NewHttpProxy()
	mitmHandler, err := mps.NewMitmHandlerWithCert(
		proxyInstance.Ctx,
		crtBytes,
		keyBytes,
	)
	if err != nil {
		log.Panic(err)
	}
	proxyInstance.HandleConnect = mitmHandler
        log.Fatal(http.ListenAndServe(fmt.Sprintf("0.0.0.0:%d", config.ListenPort), proxyInstance))
```

**Comment by telanflow** [comment]
Has the certificate file been imported into the system?

**Comment by hazcod** [comment]
Yes, using:
```go
	crtBytes, err := ioutil.ReadFile(config.CACertPath)
	if err != nil {
		log.Fatal(err)
	}

	keyBytes, err := ioutil.ReadFile(config.CAKeyPath)
	if err != nil {
		log.Fatal(err)
	}
```

They are RSA 4k.

**Comment by telanflow** [comment]
The MITM proxy needs to import the certificate file into the trusted Root Certificate Authority in the system.

You can look at this [MITM readme](https://github.com/telanflow/mps/blob/master/examples/mitm-proxy/README.md)

**Comment by hazcod** [comment]
@telanflow thanks, I drilled it down to `signHost` hardcoding the key/cert-size to 2048 bits while my CA was 4096 bits.
Edit: can you detect the used size of the CA?

**Comment by telanflow** [comment]
Ok, I'll try to modify it later.
